

all :
	@cd src && $(MAKE)
	cp -f src/sudoku ./

report : 
	@cd src && $(MAKE) report
	
clean :
	@cd src && $(MAKE) clean
	rm -rf sudoku
	
help:
	@echo "Usage:"
	@echo " make [all]\t\tBuild the software"
	@echo " make clean\t\tRemove all files generated by make"
	@echo " make help\t\tDisplay this help"	

.PHONY: all report clean help
